
spring:
  #  main:
  #    allow-bean-definition-overriding: true
  datasource: #数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1qk33f8jgb55c7g.mysql.rds.aliyuncs.com:3306/monitor?allowMultiQueries=true&serverTimezone=GMT%2B8&characterEncoding=utf8
    username: dev_read
    password: -v1pI29Lkbczkx4

    #hikari数据库连接池
    hikari:
      initial-size: 5 #初始化连接数
      max-active: 20 #最大活动连接
      max-wait: 60000 #指定连接池等待连接返回的最大等待时间，毫秒单位
      min-evictable-idle-time-millis: 1800000 #连接池空闲连接的有效时间 ，设置30分钟
      min-idle: 5 #最小空闲连接
      stat-view-servlet:
        allow: true #监控页面启动
      test-on-borrow: true #获取连接时测试是否可用
      time-between-eviction-runs-millis: 600000 #空闲连接回收的时间间隔，与test-while-idle一起使用，设置10分钟
      validation-query: SELECT 1 FROM DUAL

  redis:
    database: 1 # Redis数据库索引（默认为0）
    host: 192.168.1.113 # Redis服务器地址
    password: YN4lu2RIFMj5Qnt # Redis服务器连接密码
    port: 6379 # Redis服务器连接端口
    timeout: 6000 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接

zookeeper:
  url: 192.168.1.113:2181
  config-name: /monitor